"""init

Revision ID: 1452c12ac821
Revises: 
Create Date: 2021-10-06 15:35:14.925352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1452c12ac821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('stime', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(length=16), nullable=True),
    sa.Column('uuid', sa.String(length=256), nullable=True),
    sa.Column('qid', sa.String(length=16), nullable=True),
    sa.Column('hid', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=16), nullable=False),
    sa.Column('nid', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('stime', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('texts')
    # ### end Alembic commands ###
