"""add IP adress

Revision ID: 54e756eb0689
Revises: 6575f2d5583e
Create Date: 2021-10-14 17:51:03.846866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e756eb0689'
down_revision = '6575f2d5583e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ip')
    # ### end Alembic commands ###
