"""add admin info

Revision ID: 58516925b1f4
Revises: 95224f269a6c
Create Date: 2021-12-02 17:50:46.697308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58516925b1f4'
down_revision = '95224f269a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAccept', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isShow', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAdmin')
    op.drop_column('users', 'isShow')
    op.drop_column('users', 'isAccept')
    # ### end Alembic commands ###
