"""update

Revision ID: 6575f2d5583e
Revises: 1452c12ac821
Create Date: 2021-10-11 18:02:31.858656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6575f2d5583e'
down_revision = '1452c12ac821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('tid', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'tid')
    # ### end Alembic commands ###
