"""addmid

Revision ID: 6ce2db35b8b2
Revises: 54e756eb0689
Create Date: 2021-10-30 13:16:34.728896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce2db35b8b2'
down_revision = '54e756eb0689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
